# Site settings
title: Emre YILMAZ
email: e@emre.xyz
description: "very personal blog of emre yilmaz"
baseurl: ""
url: "http://emre.xyz"
username: delirehberi

# Build settings
markdown: kramdown
#permalink: pretty
highlighter: rouge
paginate: 5
paginate_path: "/sayfa:num"
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
