# Site settings
title: Emre YILMAZ
email: e@emre.xyz
description: "very personal blog of aybars cengaver"
baseurl: ""
url: "http://emre.xyz"
username: aybarscengaver

# Build settings
markdown: kramdown
#permalink: pretty
highlighter: pygments
paginate: 5
paginate_path: "/sayfa:num"
